### ISSUE TITLE
Missin SongOfDoom/DB-TheMessageToTheFish.ogg

### ISSUE THREAD

**Issue by cazfi** [jwrober/SongOfDoom#2]
I got a "Cannot find audio file SongOfDoom/DB-TheMessageToTheFish.ogg for tag music_classical_peace" error message.

The musicspec refers to that file, but it's not installed by the .mpdl.

**Comment by jwrober** [comment]
The file is "SongOfDoom/DB1-TheMessageToTheFish.ogg" The error is actually in the musicspec file.

**Comment by jwrober** [comment]
Closed/fixed. Updated version of the two modpack files to show change.
